website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length,InputRequired, EqualTo

class PostForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=100)])
    submit = SubmitField('Login')

class SignUpForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email()])
    user_name = StringField('User Name', validators=[InputRequired(), Length(min=4, max=25)])
    password1 = PasswordField('Password', validators=[InputRequired(), Length(min=8)])
    password2 = PasswordField('Confirm Password', validators=[InputRequired(), EqualTo('password1')])
    submit = SubmitField('Sign Up')


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    user_name = db.Column(db.String(150), unique=True)
    memories = db.relationship('Memorie', backref='user', lazy=True)
    likes = db.relationship('Like', backref='user', lazy=True)
class Memorie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    likes = db.relationship('Like', backref='post', lazy=True, cascade="all, delete-orphan")

class Like(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('memorie.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path
from flask_wtf.csrf import CSRFProtect
from os import path, getcwd

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    DB_NAME = "database.db"

    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{path.join(getcwd(), 'instance', DB_NAME)}"
    
    db.init_app(app)

    csrf = CSRFProtect()
    csrf.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Memorie, Like

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    db_path = path.join(getcwd(), 'instance', DB_NAME)
    if not path.exists(db_path):
        with app.app_context():
            db.create_all()
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import User, LoginForm, SignUpForm
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template('login.html', user=current_user, form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', category='success')
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = SignUpForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            email = form.email.data
            user_name = form.user_name.data
            password1 = form.password1.data
            password2 = form.password2.data

            user = User.query.filter_by(email=email).first()
            if user:
                message = 'Email already exists.'
                return jsonify({'success': False, 'message': message})
            elif password1 != password2:
                message = 'Passwords do not match.'
                return jsonify({'success': False, 'message': message})
            else:
                new_user = User(email=email, user_name=user_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('sign-up.html', user=current_user, form=form)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Memorie, User, Like, PostForm
from . import db

views = Blueprint('views', __name__)

@views.route('/',methods=['GET', 'POST'])
@login_required
def home():
    return render_template('home.html', user=current_user)

@views.route('/main')
@login_required
def main():
    posts = Memorie.query.all()
    liked_posts = [like.post_id for like in current_user.likes]
    return render_template('index.html', user=current_user, posts=posts, liked_posts=liked_posts)

@views.route('/post', methods=['POST'])
@login_required
def add_post():
    data = request.get_json()
    content = data.get('content')

    if not content:
        return jsonify({'error': 'Content is required'}), 400

    new_post = Memorie(data=content, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()

    return jsonify({'message': 'Post created successfully'}), 201

@views.route('/post/<int:post_id>/like', methods=['POST'])
@login_required
def like_post(post_id):
    post = Memorie.query.get_or_404(post_id)

    like = Like.query.filter_by(user_id=current_user.id, post_id=post.id).first()

    if like:
        db.session.delete(like)
        db.session.commit()
        status = 'unliked'
    else:
        new_like = Like(user_id=current_user.id, post_id=post.id)
        db.session.add(new_like)
        db.session.commit()
        status = 'liked'

    # Re-query post to get updated like count
    post = Memorie.query.get_or_404(post_id)
    like_count = len(post.likes)

    return jsonify({'status': status, 'like_count': like_count})
@views.route('/post/<int:post_id>/delete', methods=['DELETE'])
@login_required
def delete_post(post_id):
    post = Memorie.query.get_or_404(post_id)
    
    # Check if the current user is authorized to delete the post
    if post.user_id != current_user.id:
        return jsonify({'error': 'You are not authorized to delete this post'}), 403

    # Delete all likes related to this post
    likes = Like.query.filter_by(post_id=post.id).all()
    for like in likes:
        db.session.delete(like)

    # Delete the post
    db.session.delete(post)
    db.session.commit()
    
    return jsonify({'message': 'Post deleted successfully'}), 200
@views.route('/search')
@login_required
def search():
    username = request.args.get('username')
    if username:
        users = User.query.filter(User.user_name.ilike(f'%{username}%')).all()
        users_data = [{'id': user.id, 'user_name': user.user_name} for user in users]
        return jsonify({'users': users_data})
    return render_template('search.html', user=current_user)

@views.route('/user/<int:user_id>/posts')
@login_required
def get_user_posts(user_id):
    user = User.query.get(user_id)
    if user:
        posts = Memorie.query.filter_by(user_id=user_id).all()
        posts_data = [{'id': post.id, 'content': post.data, 'date': post.date.strftime('%Y-%m-%d'), 'likes': len(post.likes), 'liked': current_user.id in [like.user_id for like in post.likes]} for post in posts]
        return jsonify({'posts': posts_data})
    return jsonify({'posts': []})

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark ">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

website/templates/home.html
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
<main class='wrapper'>
    <header class='header'>
        <div class='header__logo'>Memoriat</div>
        <div class='header__right'>
            <p>
                <span class='header__language header__active'>EN</span>
                <span class='header__language'>AR</span>
            </p>
            <div class='header__diamond'></div>
        </div>
    </header>
    <nav class='menu'>
        <ul>
            <a href="{{ url_for('views.main') }}">Make a memorie</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
        </ul>
    </nav>
    <div class='bg__pattern'></div>
    <div class='bg__image'></div>
</main>
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container mt-4">
    <nav class='menu'>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Return to home page</a></li>
            <li><a href="{{ url_for('views.search') }}" class="btn btn-secondary">Search Users</a></li>
        </ul>
    </nav>
    <h1>Welcome, {{ user.user_name }}</h1>

    <form id="postForm" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <textarea id="postContent" name="content" class="form-control" rows="3"
                placeholder="What's on your mind?"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>

    <hr>

    <div class="posts">
        {% for post in posts %}
        {% if post.user_id == user.id %}
        <div class="card my-3" id="post-{{ post.id }}">
            <div class="card-body d-flex justify-content-between align-items-center">
                <p>{{ post.data }}</p>
                <footer class="blockquote-footer">
                    Posted by {{ post.user.user_name }} on {{ post.date.strftime('%Y-%m-%d') }}
                </footer>
                <p>Likes: <span class="likes-count">{{ post.likes|length }}</span></p>
                <button class="like-btn" data-post-id="{{ post.id }}">
                    {% if post.id in liked_posts %}Unlike{% else %}Like{% endif %}
                </button>
                <button class="delete-btn btn btn-danger btn-sm" data-post-id="{{ post.id }}">Delete</button>
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('.like-btn').forEach(button => {
            button.addEventListener('click', function () {
                const postId = this.getAttribute('data-post-id');

                fetch(`/post/${postId}/like`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token() }}'
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'liked') {
                            this.textContent = 'Unlike';
                        } else {
                            this.textContent = 'Like';
                        }
                        this.closest('.card-body').querySelector('.likes-count').textContent = data.like_count;
                    });
            });
        });
    });
    document.addEventListener('DOMContentLoaded', function () {
        const postForm = document.getElementById('postForm');
        const csrfToken = document.querySelector('input[name="csrf_token"]').value;

        postForm.addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            const postContent = document.getElementById('postContent').value;

            fetch('{{ url_for('views.add_post') }}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({ content: postContent })
            })
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        throw new Error('Network response was not ok.');
                    }
                })
                .then(data => {
                    console.log(data);
                    location.reload(); // Reload the page to see the new post
                })
                .catch(error => console.error('Error:', error));
        });

        document.querySelectorAll('.delete-btn').forEach(button => {
            button.addEventListener('click', function () {
                const postId = this.getAttribute('data-post-id');

                fetch(`/post/${postId}/delete`, {
                    method: 'DELETE',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken
                    }
                })
                    .then(response => {
                        if (response.ok) {
                            return response.json();
                        } else {
                            throw new Error('Network response was not ok.');
                        }
                    })
                    .then(data => {
                        console.log(data);
                        document.getElementById(`post-${postId}`).remove();
                    })
                    .catch(error => console.error('Error:', error));
            });
        });
    });
</script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
<form id="loginForm" method="POST" action="{{ url_for('auth.login') }}">
  {{ form.hidden_tag() }}
  <div class="ring">
    <i style="--clr:#82a8b3;"></i>
    <i style="--clr:#f6eadc;"></i>
    <i style="--clr:#0d1345;"></i>
    <div class="login">
      <h2>Login</h2>
      <div class="form-group">
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
      <div class="links">
        <a href="sign-up">Signup</a>
      </div>
    </div>
  </div>
</form>

<!-- <script>
  document.addEventListener('DOMContentLoaded', function () {
    const form = document.getElementById('loginForm');
    form.addEventListener('submit', function (event) {
      event.preventDefault();

      const csrfToken = document.querySelector('input[name=csrf_token]').value;
      const formData = new FormData(form);
      formData.append('csrf_token', csrfToken);

      fetch(form.action, {
        method: form.method,
        body: formData,
        headers: {
          'X-CSRFToken': csrfToken
        }
      }).then(response => {
        return response.text();
      }).then(data => {
        console.log(data);
        // Handle success or error
      }).then((_res) => {
        window.location.href = "/";
      });
    });

  });

</script> -->

{% endblock %}

website/templates/search.html
{% extends "base.html" %}

{% block title %}
Search Users
{% endblock %}

{% block content %}
<div class="container mt-4">
    <nav class='menu'>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Return to home page</a></li>
            <li><a href="{{ url_for('views.main') }}" class="btn btn-secondary">main</a></li>
        </ul>
    </nav>
    <h1>Search Users</h1>
    <form id="searchForm" method="GET">
        <div class="form-group">
            <input type="text" id="username" name="username" class="form-control" placeholder="Enter username">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <div id="searchResults" class="mt-4">
        <!-- Search results will be displayed here -->
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        function attachLikeButtonListeners() {
            document.querySelectorAll('.like-btn').forEach(button => {
                button.addEventListener('click', function () {
                    const postId = this.getAttribute('data-post-id');
                    console.log(`Liking Post ID: ${postId}`); // Debugging line

                    if (!postId) {
                        console.error('Post ID is missing or undefined');
                        return;
                    }

                    fetch(`/post/${postId}/like`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token() }}'
                        }
                    })
                        .then(response => {
                            console.log('Response status:', response.status); // Debugging line
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log('Response data:', data); // Debugging line
                            if (data.status === 'liked') {
                                this.textContent = 'Unlike';
                            } else {
                                this.textContent = 'Like';
                            }
                            this.closest('.card-body').querySelector('.likes-count').textContent = data.like_count;
                        })
                        .catch(error => console.error('Error liking post:', error));
                });
            });
        }

        // Initial setup of like buttons
        attachLikeButtonListeners();

        // Search form submission
        const searchForm = document.getElementById('searchForm');
        searchForm.addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            const username = document.getElementById('username').value;

            fetch(`{{ url_for('views.search') }}?username=${username}`)
                .then(response => response.json())
                .then(data => {
                    const resultsContainer = document.getElementById('searchResults');
                    resultsContainer.innerHTML = '';

                    if (data.users.length > 0) {
                        data.users.forEach(user => {
                            const userElement = document.createElement('div');
                            userElement.innerHTML = `
                                <div class="card my-2">
                                    <div class="card-body">
                                        <h5 class="card-title">${user.user_name}</h5>
                                        <button class="btn btn-secondary view-posts-btn" data-user-id="${user.id}">View Posts</button>
                                    </div>
                                </div>
                            `;
                            resultsContainer.appendChild(userElement);
                        });

                        document.querySelectorAll('.view-posts-btn').forEach(button => {
                            button.addEventListener('click', function () {
                                const userId = this.getAttribute('data-user-id');
                                fetch(`/user/${userId}/posts`)
                                    .then(response => response.json())
                                    .then(postsData => {
                                        const postsContainer = document.createElement('div');
                                        postsContainer.classList.add('posts-container');

                                        postsData.posts.forEach(post => {
                                            const postElement = document.createElement('div');
                                            postElement.innerHTML = `
                                                <div class="card my-2">
                                                    <div class="card-body">
                                                        <p>${post.content}</p>
                                                        <footer class="blockquote-footer">Posted on ${post.date}</footer>
                                                        <p>Likes: <span class="likes-count">${post.likes}</span></p>
                                                        <button class="like-btn" data-post-id="${post.id}">
                                                            ${post.liked ? 'Unlike' : 'Like'}
                                                        </button>
                                                    </div>
                                                </div>
                                            `;
                                            postsContainer.appendChild(postElement);
                                        });

                                        resultsContainer.appendChild(postsContainer);

                                        // Reattach event listeners to new like buttons
                                        attachLikeButtonListeners();
                                    })
                                    .catch(error => console.error('Error fetching posts:', error));
                            });
                        });
                    } else {
                        resultsContainer.innerHTML = '<p>No users found</p>';
                    }
                })
                .catch(error => console.error('Error:', error));
        });
    });
</script>
{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %}
{% block
content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/sign-up.css') }}">
<form id="SignUpForm" method="POST" action="{{ url_for('auth.sign_up') }}">
    {{ form.hidden_tag() }}
    <div class="ring">
        <i style="--clr:#82a8b3;"></i>
        <i style="--clr:#f6eadc;"></i>
        <i style="--clr:#0d1345;"></i>
        <div class="login">
            <h2>Sign up</h2>
            <div class="form-group">

                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="user_name" name="user_name" placeholder="Enter user name" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password1" name="password1"
                    placeholder="Enter password" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password2" name="password2"
                    placeholder="Confirm password" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <div class="links">
                <a href="/login">Login</a>
            </div>
        </div>
    </div>
</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('SignUpForm');
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            const csrfToken = document.querySelector('input[name=csrf_token]').value;
            const formData = new FormData(form);
            formData.append('csrf_token', csrfToken);

            fetch(form.action, {
                method: form.method,
                body: formData,
                headers: {
                    'X-CSRFToken': csrfToken
                }
            }).then(response => {
                return response.text();
            }).then(data => {
                console.log(data);
                // Handle success or error
            }).then((_res) => {
                window.location.href = "/";
            });
        });

    });
</script>

{% endblock %}